# name: NuGet Package Deploy Task

# on:
#   push:
#     branches:
#       - master
#   pull_request:
#     branches:
#       - master

# jobs:
#   build:
 
#     runs-on: ubuntu-latest
     
#     steps:
#     - uses: actions/checkout@v1
#     - name: Setup .NET Core
#       uses: actions/setup-dotnet@v1
#       with:
#         dotnet-version: 3.1.201
#     - name: Build with dotnet
#       run: dotnet build --configuration Release
#   deploy:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#       - name: Pack with dotnet
#         run: dotnet pack Allegiance.Blazor.NoUiSlider.Core.csproj --output nuget-packages --configuration Release
#       - name: Push with dotnet
#         run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{ secrets.NUGET_ACCOUNT }} --source https://api.nuget.org/v3/index.json

name: NuGet Package Deploy Task

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Test
        run: dotnet build --configuration Release
        working-directory: ./Allegiance.Blazor.NoUiSlider.Core

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: ./Allegiance.Blazor.NoUiSlider.Core/bin/Release/netcoreapp3.1/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: app
          path: ./Allegiance.Blazor.NoUiSlider.Core

      - uses: actions/checkout@v2
      - name: Pack with dotnet
        run: dotnet pack Allegiance.Blazor.NoUiSlider.Core.csproj --output nuget-packages --configuration Release
      - name: Push with dotnet
        run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{ secrets.NUGET_ACCOUNT }} --source https://api.nuget.org/v3/index.json
